import os
import json
import matplotlib.pyplot as plt
import re

# Yes the vast majority of this code is chatgpt generated and I'm not ashamed of it
# is late at night and I'm tired. I made this whole project by myself and I'm proud of it
# I'm not going to spend time writing code that I can generate in 5 seconds. Additionally,
# I had to fine tunning the code generated by chatgpt to make it work.


def extract_byzantine_number(filename):
    match = re.search(r"byzantine_nodes_(\d+)_", filename)
    if match:
        return int(match.group(1))
    return None


def extract_commit_number(filename):
    match = re.search(r"commit_(\d+)_", filename)
    if match:
        return int(match.group(1))
    return None


def read_json_files_byzantine_nodes(directory):
    # Lists to store x-axis (current_commit) and y-axis (other values)
    x_axis = []
    metrics = {
        "byzantine_delete_counter": [],
        "byzantine_insert_counter": [],
        "delete_requeue_counter": [],
        "delete_requeue_limit": [],
        "delete_stash_counter": [],
        "delete_valid_counter": [],
        "insert_distance_greater_than_one": [],
        "insert_request_limit_counter": [],
        "insert_stash_fail_counter": [],
        "insert_valid_counter": [],
    }

    # Get all JSON files in the directory
    files = [f for f in os.listdir(directory) if f.endswith(".json")]

    # Sort files by commit number
    files.sort(key=lambda f: extract_byzantine_number(f))

    # Read through all JSON files in the correct order
    for filename in files:
        filepath = os.path.join(directory, filename)
        with open(filepath, "r") as file:
            data = json.load(file)
            byzantine_number = extract_byzantine_number(filename)
            x_axis.append(byzantine_number)

            # Append values for each relevant metric
            for key in metrics:
                metrics[key].append(data[key])

    # new_metrics = {}
    # for key in metrics:
    #     if key == "delete_stash_counter":
    #         new_metrics["Delete_Stash_Messages"] = metrics[key]
    #     if key == "delete_valid_counter":
    #         new_metrics["Delete_Valid_Messages"] = metrics[key]
    #     if key == "insert_distance_greater_than_one":
    #         new_metrics["Ahead_of_Local_Clock"] = metrics[key]
    #     if key == "insert_valid_counter":
    #         new_metrics["Insert_Valid_Messages"] = metrics[key]

    return x_axis, metrics


def read_json_files_no_byzantine_nodes(directory):
    # Lists to store x-axis (current_commit) and y-axis (other values)
    x_axis = []
    metrics = {
        "delete_stash_counter": [],
        "delete_valid_counter": [],
        "insert_distance_greater_than_one": [],
        "insert_valid_counter": [],
    }

    # Get all JSON files in the directory
    files = [f for f in os.listdir(directory) if f.endswith(".json")]

    # Sort files by commit number
    files.sort(key=lambda f: extract_commit_number(f))

    # Read through all JSON files in the correct order
    for filename in files:
        filepath = os.path.join(directory, filename)
        with open(filepath, "r") as file:
            data = json.load(file)
            commit_number = extract_commit_number(filename)
            x_axis.append(commit_number)

            # Append values for each relevant metric
            for key in metrics:
                metrics[key].append(data[key])

    new_metrics = {}
    for key in metrics:
        if key == "delete_stash_counter":
            new_metrics["Delete_Stash_Messages"] = metrics[key]
        if key == "delete_valid_counter":
            new_metrics["Delete_Valid_Messages"] = metrics[key]
        if key == "insert_distance_greater_than_one":
            new_metrics["Ahead_of_Local_Clock"] = metrics[key]
        if key == "insert_valid_counter":
            new_metrics["Insert_Valid_Messages"] = metrics[key]

    return x_axis, new_metrics


# Function to normalize a list of values
def normalize(values):
    if not values:
        return values
    min_val = min(values)
    max_val = max(values)
    if min_val == max_val:
        return [1] * len(values)
    else:
        return [(value - min_val) / (max_val - min_val) for value in values]


# Function to generate the plot with normalized values
def plot_metrics(x_axis, metrics, xlabel, title):

    # Normalize metrics
    normalized_metrics = {key: normalize(values) for key, values in metrics.items()}

    # Create a plot for each metric
    fig, ax = plt.subplots(figsize=(10, 8))
    ax.set_xlabel(xlabel)

    # Plot each normalized metric
    for metric, values in normalized_metrics.items():
        if any(values):  # Plot only if there are non-zero values
            ax.plot(x_axis, values, label=metric.replace("_", " ").title())

    # Customize the plot
    ax.legend()
    ax.set_title(title)
    ax.grid(True)

    # Show the plot
    plt.tight_layout()
    plt.show()


# Main function to execute the script
def main():
    script_dir = os.path.dirname(os.path.abspath(__file__))
    directory = os.path.join(script_dir, "../debug/metadata/no_byzantine_nodes")
    directory_byzantine = os.path.join(script_dir, "../debug/metadata/byzantine_nodes")
    x_axis_no_byzantine, metrics_no_byzantine = read_json_files_no_byzantine_nodes(
        directory
    )
    # plot_metrics(
    #     x_axis_no_byzantine, metrics_no_byzantine, "Commit Number", "Normalized Metric Values Over Commit Numbers"
    # )
    x_axis_byzantine, metrics_byzantine = read_json_files_byzantine_nodes(
        directory_byzantine
    )
    plot_metrics(
        x_axis_byzantine,
        metrics_byzantine,
        "Number of Byzantine Nodes",
        "Normalized Metric Values Over Byzantine Nodes")


if __name__ == "__main__":
    main()
